### ISSUE TITLE
New Chromium sends opus+red FMTP, breaks SDP parsing

### ISSUE THREAD

**Issue by sax** [membraneframework/ex_sdp#14]
As of the latest Chromium, this attribute is showing up in the SDP counter-offer from the browser:

`a=fmtp:63 111/111`

This gets caught in the fall-through case of `parse_param` in `ExSDP.Attribute.FMTP` and results in `{:error, :unsupported_parameter}`.

https://groups.google.com/g/discuss-webrtc/c/5761etCrSuA

**Comment by jasonwc** [comment]
Here's specifically where they discuss this feature:

https://bugs.chromium.org/p/webrtc/issues/detail?id=11640

They specifically mention how they generate that new attribute:

```
generates a fmtp line like
  a=fmtp:<red payloadtype> <opus payloadtype>/<opus payloadtype>
  ```

**Comment by jasonwc** [comment]
Here's some more context and a discussion in Janus:

https://github.com/meetecho/janus-gateway/pull/2685
